name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: User node js
        uses: actions/setup-node@master
        with:
          node-version: '14'
      - name: Install Dependencies
        run: make install
      - name: Test & coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
